# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
            ],
        ),
    ]
